// 11.16.25
// WEAPON NOTES
// 1 - CROWBAR, SATCHEL, HANDGREN, TRIPMINE
// 2 - HANDGUN, .357
// 3 - SHOTGUN
// 4 - MP5
// 5 - CROSSBOW
// 6 - HORNETGUN, SNARK
// 7 - ROCKET LAUNCHER
// 8 - TAU, GLUON

// glock
// 8 dmg
// 0 - 15 : 16 fps draw
// 16 - 27 : 20 fps shoot
// 28 - 39 : 20 fps shoot slideback
// 40 - 81 : 18 fps reload slideback
// 82 - 123 : 18 fps reload
// 124 - 154 : 8 fps idle1
// 155 - 175 : 8 fps idle2
// 176 - 201 : 7 fps idle3
// 202 - 217 : 16 fps holster


//today's progress
// Finished MP5
// starting on conv. glock mdl
// fixed hl explosions ( mostly)
// added shell casings
// footsteps
// started on conv spas, crowbar

//11.17.25

//shotgun
// 0 - 10 : draw 20 fps
// 11 - 31 : shoot 20 fps
// 32 - 52 : big shoot 13 fps
// 53 - 61 : reload start 12 fps
// 62 - 71 : insert shell 16 fps
// 72 - 82 : finish reloading 13 fps
// 83 - 103 : idle1 fps 9
// 104 - 124 : idle2 fps 9
// 125 - 185 : idle3 fps 12
// 186 - 193 : holster 20 fps

// Finished SHOTGUN
// finished GLOCK